services:
  code-server:
    build:
      context: .
      args:
        USERNAME: ${USER:?USER must be set}
    working_dir: /data/zusers/${USER:?USER must be set}
    container_name: code-server
    environment:
      - TZ="America/New_York"
    volumes:
      - /data:/data
      - /zata:/zata
    restart: unless-stopped
